POST http://localhost:3000/addiction/create
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiZmlsbGRkZGRAZ21haWwuY29tIiwibG9naW4iOiJzb25pYzQ3IiwiaWF0IjoxNzQ3NTYzNTk0LCJleHAiOjE3NDc1NjcxOTQsImF1ZCI6ImVsb2FzZCIsImlzcyI6ImRzYWRzYSJ9.gF_b3Owtkuxyv9an_s1FCdQ6_TEKwHhPSqLR3HcFHto
Content-Type : application/json

{
  "addictionName": "Saaaamoking",
  "notes": "Rzudddcam paczkę dziennie",
  "startTime": "2025-05-17T09:30:00.000Z"
}
